services:
  postgres:
    image: postgres:15
    container_name: controlbits-postgres
    restart: always
    environment:
      POSTGRES_USER: controlbits
      POSTGRES_PASSWORD: controlbits123
      POSTGRES_DB: controlbits_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
